### ISSUE TITLE
'Sealed override' is shown as 'virtual'

### ISSUE THREAD

**Issue by jnm2** [PublicApiGenerator/PublicApiGenerator#112]
I tried to fix it but it looks like abandoning CodeDOM might be necessary. See https://github.com/ApiApprover/ApiApprover/pull/111.

**Comment by sungam3r** [comment]
> abandoning CodeDOM might be necessary

Or forking it.

**Comment by danielmarbach** [comment]
Once the event modifier stuff is in we could technically do the same trickery with methods

**Comment by danielmarbach** [comment]
I'm not saying I like it but so far Code Dom has proven itself fairly flexible :)

**Comment by sungam3r** [comment]
Of course, with CodeDom and replacement magic you can achieve much more than just with CodeDom.

**Comment by danielmarbach** [comment]
Added https://github.com/PublicApiGenerator/PublicApiGenerator/pull/152 for the method part. I have to finish 6 tests that came from the event modifier changes but other than that it seems that most cases are now addressed

**Comment by danielmarbach** [comment]
PR is ready to go. In case nobody chimes in with thoughts I will merge it tomorrow evening or so

**Comment by danielmarbach** [comment]
Added https://github.com/PublicApiGenerator/PublicApiGenerator/pull/155 for the properties part

**Comment by danielmarbach** [comment]
I think this is reasonably addressed. Pretty sure there is an edge case that isn't covered yet but we can deal with those when the need arises.

**Comment by danielmarbach** [comment]
Do you want to give beta 8 a stab? There is a known issue with a bit too much whitespace with the new modifer that I already sent a PR for. Other than that I hope this is it for 10.0.0
