### ISSUE TITLE
10.0.0 Release

### ISSUE THREAD

**Issue by danielmarbach** [PublicApiGenerator/PublicApiGenerator#159]
- [x] Build tag
- [x] Assemble release notes
- [x] Push package
- [x] Create next milestone
- [x] Close milestone
- [x] Tweet, mentioning contributors

## Current release notes

Changes:

- Remove support for .NET 4.0 [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/89)
- Read-only structs support [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/84)
- In-modifier support [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/85)
- Unsafe modifier support [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/120)
- Support for default keyword for non primitive structs [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/88)
- Removing empty attribute parentheses and Attribute suffix if present [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/118
- Fix order of static and readonly keywords [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/122)
- Fix order of members within a type, by @adamralph  [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/138)
- Volatile public field support [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/123)
- Fix support for named indexers [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/136)
- More advanced support for Property, event and method modifiers 
 - Event modifiers [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/130)
 - Property modifiers [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/155)
 - Method modifiers [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/152)
- C# 8 nullable reference type support, by @sungam3r and @jnm2 [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/115)
- Embedded PDB in package and source for better source-stepping [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/131/)
- Introduce `ApiGeneratorOptions` to configure the generator [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/129)
- Extension methods as public API for the generator [PR](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/134)

For more information see the [related milestone](https://github.com/PublicApiGenerator/PublicApiGenerator/milestone/17).

**Comment by jnm2** [comment]
> C# 8 nullable reference type support, by @jnm2 and @sungam3r

Ivan did all the work in my opinion :D
