### ISSUE TITLE
From 9.x to 10.0.0: The call is ambiguous between the following methods or properties

### ISSUE THREAD

**Issue by mauroservienti** [PublicApiGenerator/PublicApiGenerator#162]
I have a very simple test case like the following:

```
[TestMethod]
[UseReporter(typeof(DiffReporter))]
public void Approve_API()
{
   var publicApi = ApiGenerator.GeneratePublicApi(typeof(SomeTypeName).Assembly);

   Approvals.Verify(publicApi);
}
```
By upgrading from latest 9 minor to 10.0.0 I get the following error:

> The call is ambiguous between the following methods or properties: 'ApiGenerator.GeneratePublicApi(Assembly, ApiGeneratorOptions?)' and 'ApiGenerator.GeneratePublicApi(Assembly, Type[]?, bool, string[]?, string[]?)'

The fix is as simple as:

```
var publicApi = ApiGenerator.GeneratePublicApi(typeof(SomeTypeName).Assembly, options: null);
```

so that the compiler is happy in selecting the right overload. However it's not so trivial when the number of projects to update is large.

Was this signature change intended? Am I missing something obvious?

**Comment by danielmarbach** [comment]
Yes it was an intended change as part of https://github.com/PublicApiGenerator/PublicApiGenerator/pull/134

See the samples in our readme

so your case would need to be changed to

```
[TestMethod]
[UseReporter(typeof(DiffReporter))]
public void Approve_API()
{
   var publicApi = typeof(SomeTypeName).Assembly.GeneratePublicApi();

   Approvals.Verify(publicApi);
}
```

**Comment by mauroservienti** [comment]
Got it, thanks @danielmarbach.
