### ISSUE TITLE
Build batch fails when invoked from outside project directory

### ISSUE THREAD

**Issue by atifaziz** [PublicApiGenerator/PublicApiGenerator#164]
Suppose the project is checked out at `A:\PublicApiGenerator` and the current working directory is `C:\`. Then, running `A:\PublicApiGenerator\build.cmd` in a Windows Command Prompt or PowerShell terminal fails with:

    MSBUILD : error MSB1009: Project file does not exist.
    Switch: ./src/PublicApiGenerator.sln

**Comment by danielmarbach** [comment]
Thanks!
