### ISSUE TITLE
Wrong package version may be used silently (NU1603)

### ISSUE THREAD

**Issue by atifaziz** [PublicApiGenerator/PublicApiGenerator#168]
I have been using this tool against packages coming off a build pipeline and I was getting puzzled on some occasions, and for quite some time, why the output would be from a different version than the expected one. After enabling verbose output, I finally discovered that warning [NU1603](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1603) was being issued along the lines of:

    'PackageA' 4.0.0 depends on 'PackageB' (>= 4.0.0) but 4.0.0 was not found. An approximate best match of 5.0.0 was resolved.

I propose a default behaviour of treating [warnings as errors](https://github.com/NuGet/Home/wiki/NuGet-Errors-and-Warnings) and a switch that suppresses warnings if someone wants to revert to the current behaviour.

**Comment by danielmarbach** [comment]
Exact package version can be used, I updated the readme with a sample as part of #172
