### ISSUE TITLE
Write API output to STD out

### ISSUE THREAD

**Issue by danielmarbach** [PublicApiGenerator/PublicApiGenerator#173]
Idea from @atifaziz 

> You see, if you change the tool such that it writes the public API to standard output in some future version (that I'd like to propose 😉)

**Comment by danielmarbach** [comment]
@atifaziz do you have have a recommendation on how the tool should handle API outputs to multiple target frameworks?

Currently, the tool creates a file per target framework. Would a `Console.WriteLine` per target framework be enough?

**Comment by atifaziz** [comment]
> do you have have a recommendation on how the tool should handle API outputs to multiple target frameworks?

The tool would need two modes of operation:

1. Generate API to standard output if only a single target framework is given and the `--output-directory` argument is absent.
2. Generate files per framework API like now but print the generate file paths to standard output.

If the `--output-directory` argument is supplied then it's clear that the user wants a file generated even if a single target framework is given, and in which case, the tool should enter mode 2.

However, I would argue that we shouldn't even bother with multiple target frameworks. If the tool just works with one target framework then the user can just use loop from the shell to invoke the tool for each framework and redirect the output to file if they prefer file generation:

Windows example:

```cmd
for %f in (netcoreapp2.1 netcoreapp3.1) do ^
  generate-public-api --package foobar --package-version 42.0.0 --target-framework %f ^
    > foobar.%f.received.txt
```

PowerShell example:

```ps1
'netcoreapp2.1', 'netcoreapp3.1' |
  % { generate-public-api --package foobar --package-version 42.0.0 --target-framework $_ |
        Out-File "foobar.$f.received.txt" -Encoding utf8 }
```

Bash example:

```sh
for f in netcore2.1 netcore3.1; do
  generate-public-api --package foobar --package-version 42.0.0 --target-framework ${f} \
    > foobar.${f}.received.txt
done
```

In essence, the tool would become very simple and just do one thing and do it well.

The only argument I see in favour of supporting a multiple-target-frameworks argument is that you want the tool invocation to be to be independent of shells (use doesn't have to adapt to the looping syntax in each shell) so you make looping through target frameworks a native feature (but as a nice-to-have and a secondary mode of operation). It does however complicate things by introducing multiple modes of operation.

**Comment by danielmarbach** [comment]
It sort of has to be independent of shell because it is shipped as a dotnet global tool to essentially any environment that supports .NET Core and global tools.

**Comment by atifaziz** [comment]
I don't think global tools are designed for shell-independence. Rather, they allow an x-plat installation of _executables_ for .NET Core based console applications (that are otherwise just DLL assemblies).

**Comment by sungam3r** [comment]
I join the view that it’s worth simplifying the tool and getting the target platform through an argument.
Like `dotnet publish`:
`error : The 'Publish' target is not supported without specifying a target framework. The current project targets multiple frameworks, please specify the framework for the published application.`

**Comment by danielmarbach** [comment]
Done via https://github.com/PublicApiGenerator/PublicApiGenerator/pull/181
