### ISSUE TITLE
Allow package sources to be specified tool argument

### ISSUE THREAD

**Issue by atifaziz** [PublicApiGenerator/PublicApiGenerator#176]
Consider adding `--package-source` argument to the tool so one can specify package feeds to use. The sources could then be just added to the `<RestoreAdditionalProjectSources>` property group in the temporary `project.csproj`.

A workaround would be to specify a working directory (via `--working-directory`) where a `nuget.config` exists in the ancestor tree with the additional sources needed but this requires a lot of ceremony and setup to get right.

**Comment by atifaziz** [comment]
For example, see atifaziz/PublicApiGenerator@0f7ed9bfb64221c0af180bbc39f24453cb0ab874. I can submit as a PR if the enhancement would be welcome.

**Comment by danielmarbach** [comment]
I think that would be a great addition. How about first getting in #177 for the public api generator tool and after that when it is merged to master bring in those additional command line params?

**Comment by atifaziz** [comment]
@danielmarbach Sound like a good plan! 👍

**Comment by danielmarbach** [comment]
@atifaziz see https://github.com/PublicApiGenerator/PublicApiGenerator/issues/176

**Comment by atifaziz** [comment]
> @atifaziz see #176

@danielmarbach You mean, [see recursion](https://www.urbandictionary.com/define.php?term=recursion)? 😁

**Comment by danielmarbach** [comment]
Ah man. Copy paste is hard on Fridays :)

https://github.com/PublicApiGenerator/PublicApiGenerator/pull/183
