### ISSUE TITLE
Question about WhitelistedNamespacePrefixes

### ISSUE THREAD

**Issue by sungam3r** [PublicApiGenerator/PublicApiGenerator#184]
Is it conceived that this property does not affect the printing of the class itself? I observe empty classes in the output. 

`WhitelistedNamespacePrefixes = new[] { }`:
```c#
namespace System.IdentityModel.Tokens.Jwt
{
    public static class JwtSecurityTokenExtensions { }
}
```

 `WhitelistedNamespacePrefixes = new[] { "System.IdentityModel.Tokens.Jwt" }`:
```c#
namespace System.IdentityModel.Tokens.Jwt
{
    public static class JwtSecurityTokenExtensions
    {
        public static bool CheckGrantOperation(this System.IdentityModel.Tokens.Jwt.JwtSecurityToken token, string operation) { }
        public static string[] GetGrantOperations(this System.IdentityModel.Tokens.Jwt.JwtSecurityToken token) { }
        public static string GetUserLogin(this System.IdentityModel.Tokens.Jwt.JwtSecurityToken token) { }
    }
}
```

**Comment by danielmarbach** [comment]
By default types are excluded in `System` or `Microsoft` namespace. Could this be a special case that we haven't considered given that this type contains extension methods that extend an excluded type?

**Comment by sungam3r** [comment]
I thought so too and tried without extension methods. The result is the same.

**Comment by Ekkeir** [comment]
The same issue for me. Is there any known solution?

**Comment by sungam3r** [comment]
@Ekkeir see #286

**Comment by sungam3r** [comment]
> Could this be a special case that we haven't considered given that this type contains extension methods that extend an excluded type?

@danielmarbach I added new option in #286 to deal with it.
