### ISSUE TITLE
[Serializable] attribute does not show up in contracts

### ISSUE THREAD

**Issue by stakx** [PublicApiGenerator/PublicApiGenerator#190]
```csharp
[Serializable] class SomeException : Exception { }
```

PublicApiGenerator won't reproduce the `[Serializable]` attribute in the generated API string&mdash;assuming default `PublicApiGeneratorOptions` which don't exclude it.

This is likely due to `SerializableAttribute` being a "pseudo" custom attribute that gets transformed to a `TypeAttributes` flag in the IL metadata. Unlike System.Reflection, Mono Cecil is more faithful to the actual metadata and won't report it as a custom attribute when querying `type.CustomAttributes` [here](https://github.com/PublicApiGenerator/PublicApiGenerator/blob/a2a24907603fc853cae38f03e18923fa0d461f85/src/PublicApiGenerator/ApiGenerator.cs#L439).

**Comment by danielmarbach** [comment]
Hmm... That means the changes introduced in https://github.com/PublicApiGenerator/PublicApiGenerator/issues/117 especially in https://github.com/PublicApiGenerator/PublicApiGenerator/pull/121 are not really working for SerializableAttributes

@stakx would you be able to send in a reproduction test and potentially give a stab a fixing it?

**Comment by stakx** [comment]
@danielmarbach &mdash; will do. I'll likely continue working on the PR I just submitted later today.

**Comment by danielmarbach** [comment]
10.1.1 is up on Nuget

**Comment by stakx** [comment]
Awesome @danielmarbach &mdash; thanks, once again, for the super quick response time!
