### ISSUE TITLE
Default parameters?

### ISSUE THREAD

**Issue by CumpsD** [PublicApiGenerator/PublicApiGenerator#199]
Any way to discover if somebody has added a default parameter to a constructor, making the public api not binary compatible?

Now it seems to pass as valid since there was 1 ctor before and now there still is only one constructor?

**Comment by danielmarbach** [comment]
PublicApiGenerator doesn't make any judgements about APIs. It just dumps out the public API structure at a given time. In order to verify API changes you need to combine PublicApiGenerator with an approval methods that either does something automatically or let a human approve the changes and make the judgement.

Does that make sense?

**Comment by CumpsD** [comment]
Yes it does. I created a small console app to load an assembly, generate the public api and write it to a text file. Then do the same with a newer version. And then I manually diffed the files.

The problem is, the output seems to be only types? No methods, no parameters. So the extra optional parameter they introduced, didn't get spotted.

Should PublicApiGenerator be capable of this functionality?

It was nothing more than Assembly.LoadFrom and then calling GeneratePublicApi() on that assembly.

**Comment by danielmarbach** [comment]
> The problem is, the output seems to be only types? No methods, no parameters. So the extra optional parameter they introduced, didn't get spotted.

That's weird. It should output all public members like this example from FluentAssertions

```
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.Versioning.TargetFramework(".NETCoreApp,Version=v2.0", FrameworkDisplayName="")]
namespace FluentAssertions
{
    public class AndConstraint<T>
    {
        public AndConstraint(T parentConstraint) { }
        public T And { get; }
    }
    public class AndWhichConstraint<TParentConstraint, TMatchedElement> : FluentAssertions.AndConstraint<TParentConstraint>
    {
        public AndWhichConstraint(TParentConstraint parentConstraint, System.Collections.Generic.IEnumerable<TMatchedElement> matchedConstraint) { }
        public AndWhichConstraint(TParentConstraint parentConstraint, TMatchedElement matchedConstraint) { }
        public TMatchedElement Subject { get; }
        public TMatchedElement Which { get; }
    }
    public static class AssertionExtensions
    {
        public static TTo As<TTo>(this object subject) { }
        public static System.Func<System.Threading.Tasks.Task> Awaiting<T>(this T subject, System.Func<T, System.Threading.Tasks.Task> action) { }
        public static System.Action Enumerating(this System.Func<System.Collections.IEnumerable> enumerable) { }
        public static System.Action Enumerating<T>(this System.Func<System.Collections.Generic.IEnumerable<T>> enumerable) { }
```

do you have a repro to share?

**Comment by CumpsD** [comment]
Sure, hold on.

[publicapi-repro.zip](https://github.com/PublicApiGenerator/PublicApiGenerator/files/4837766/publicapi-repro.zip)

In the `assets` folder you can see the output I am getting.

**Comment by danielmarbach** [comment]
Try this

```
var options = new ApiGeneratorOptions {
                WhitelistedNamespacePrefixes = new[] { "Microsoft" }
            };
            File.WriteAllText($"assets/{version}.txt", a.GeneratePublicApi(options));
```

**Comment by CumpsD** [comment]
That explains.... Thanks!
