### ISSUE TITLE
Incorrect link to License

### ISSUE THREAD

**Issue by jn-foreflight** [PublicApiGenerator/PublicApiGenerator#223]
Nuget seems to have [problems](https://github.com/NuGet/Home/issues/7601) linking to extension-less license files

![image](https://user-images.githubusercontent.com/78789299/111661987-cff8ad00-880f-11eb-8fba-2cdcdfd2aaa6.png)

Scenario: I use `Get-Package | Select-Object Id,LicenseUrl` to list all licenses in my projects and for PublicApiGenerator it prints
```
PublicApiGenerator                                              https://aka.ms/deprecateLicenseUrl
```

As far as I understand the license displayed on show on https://www.nuget.org/packages/PublicApiGenerator/
is generated upon ingestion of the nuget package where it stores the license file from `<PackageLicenseFile>` and generates a valid link to it.

If this is changed to 
```
<PackageLicenseExpression>MIT</PackageLicenseExpression>
```
the _nuget pack_ will include `https://licenses.nuget.org/MIT` in the generated .nuspec file.

Optionally use a combined approach, using `<PackageLicenseExpression>` and embedding the license file, see https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Newtonsoft.Json.csproj

**Comment by sungam3r** [comment]
I returned text license file back into repo but it's not packed into nupkg. Nupkg uses PackageLicenseExpression.
