### ISSUE TITLE
Can we get a release to fix System.CodeDom version conflict?

### ISSUE THREAD

**Issue by SimonCropp** [PublicApiGenerator/PublicApiGenerator#229]
In some test runners we are getting a version conflict for System.CodeDom:

```
Message: 
System.IO.FileNotFoundException : Could not load file or assembly 'System.CodeDom, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

  Stack Trace: 
ApiGenerator.CreatePublicApiForAssembly(AssemblyDefinition assembly, Func`2 shouldIncludeType, Boolean shouldIncludeAssemblyAttributes, String[] whitelistedNamespacePrefixes, AttributeFilter attributeFilter)
ApiGenerator.GeneratePublicApi(Assembly assembly, ApiGeneratorOptions options)
ApiExtensions.CheckApproval(Assembly assembly, String filePath) line 14
ApiApprovalTests.Run() line 14
```

It seems the [current codebase uses version 5](https://github.com/PublicApiGenerator/PublicApiGenerator/blob/master/src/PublicApiGenerator/PublicApiGenerator.csproj#L20) but the [current nuget uses 4.7](https://www.nuget.org/packages/PublicApiGenerator/#dependencies-tab)

**Comment by stakx** [comment]
@SimonCropp &ndash; yes, it's about time we pushed a release with the latest changes. I'll try to get that done as soon as I can.

**Comment by stakx** [comment]
Sorry again for the horrendous delay. I've been crazy busy, but finally found some time to push an updated package version 10.3.0 to NuGet. Went straight to the current version of System.CodeDom, which is 6.0.0.
