### ISSUE TITLE
Allow specific types to be excluded

### ISSUE THREAD

**Issue by siewers** [PublicApiGenerator/PublicApiGenerator#388]
Hi

I've just started to use this library but have encountered an unfortunate issue.

In our API, we expose a public type that is shared between our consumers. However, it is not technically public in the same sense as methods and other types in our API. Our consumers use this type to communicate the global availability of features used for feature flagging, and the type resides in our API to allow easier distribution.

As I can understand from this issue #24, it was decided that such functionality should not be added because any change to the public API is considered a breaking change.
While that makes sense, it's more complex in my specific case.

Right now, I'm using a workaround where I manually remove the type using regex. Still, I'd be more comfortable simply excluding the type directly through the options, similar to how attributes can be excluded (#45).

Are there any plans to extend the options to allow excluding specific types?

From the implementation, adding support for this would be relatively straightforward, and I would also be willing to provide a pull request if the request sounds reasonable.

**Comment by sungam3r** [comment]
@siewers @danielmarbach @adamralph I've read and decided to implement this feature. I see no burden from design and maintanability perspective. We already have `ApiGeneratorOptions.IncludeTypes` so IMO `ApiGeneratorOptions.ExcludeTypes` looks well.

**Comment by sungam3r** [comment]
https://github.com/PublicApiGenerator/PublicApiGenerator/releases/tag/11.2.0
https://www.nuget.org/packages/PublicApiGenerator/11.2.0
