### ISSUE TITLE
Add "XamlGeneratedNamespace" to list of default excluded namespaces

### ISSUE THREAD

**Issue by GeertvanHorrik** [PublicApiGenerator/PublicApiGenerator#395]
When developing apps using WPF and in debug mode, the tooling (sometimes) adds a `XamlGeneratedNamespace` namespace, "breaking" our tests. It does not generate this namespace in release mode.

I think this is only used during debug for tooling and is not part of the public API. Would you be open to a PR where this namespace is added to the list of default namespaces?

**Comment by sungam3r** [comment]
https://learn.microsoft.com/en-us/dotnet/api/xamlgeneratednamespace?view=netframework-4.8.1 says that types from that namespace are compiler generated so all of them should be excluded ootb.

**Comment by GeertvanHorrik** [comment]
Here is an example that generates it at the bottom of the file (see https://github.com/WildGums/Orchestra/blob/develop/src/Orchestra.Tests/PublicApiFacts.Orchestra_Core_HasNoBreakingChanges_Async.verified.txt#L1229):

```
namespace XamlGeneratedNamespace
{
    public sealed class GeneratedInternalTypeHelper : System.Windows.Markup.InternalTypeHelper
    {
        public GeneratedInternalTypeHelper() { }
        protected override void AddEventHandler(System.Reflection.EventInfo eventInfo, object target, System.Delegate handler) { }
        protected override System.Delegate CreateDelegate(System.Type delegateType, object target, string handler) { }
        protected override object CreateInstance(System.Type type, System.Globalization.CultureInfo culture) { }
        protected override object GetPropertyValue(System.Reflection.PropertyInfo propertyInfo, object target, System.Globalization.CultureInfo culture) { }
        protected override void SetPropertyValue(System.Reflection.PropertyInfo propertyInfo, object target, object value, System.Globalization.CultureInfo culture) { }
    }
}
```

**Comment by sungam3r** [comment]
So, `GeneratedInternalTypeHelper` is compiler generated class without CompilerGeneratedAttribute, right?

**Comment by sungam3r** [comment]
Ah, it's public, then you may achieve your goal with #394 .

**Comment by sungam3r** [comment]
I am not inclined to do this, at least yet, because the desired can be achieved by specifying the settings by the caller, avoiding a possible conflict of interest.

**Comment by GeertvanHorrik** [comment]
I understand your concerns. The reason I try to advocate for this is that it impacts all our WPF projects and I don't see why this ever should be part of the "public API" (and thus could benefit other users as well).

I think we also noticed that a lot of times, this only gets added in debug mode (not in release mode), but not 100% sure about the requirements / reasons behind this namespace.

**Comment by sungam3r** [comment]
ping @stakx and @danielmarbach for comments

**Comment by danielmarbach** [comment]
Seems to be valid to add to the default exclusions as Geert suggested if it can be done risk free

https://github.com/PublicApiGenerator/PublicApiGenerator/blob/164e2b7765455637580c0f56dea5462a6aacd2d4/src/PublicApiGenerator/ApiGeneratorOptions.cs#L78

**Comment by sungam3r** [comment]
#397

**Comment by GeertvanHorrik** [comment]
Thank you! 🙏

**Comment by sungam3r** [comment]
https://github.com/PublicApiGenerator/PublicApiGenerator/releases/tag/11.2.0
https://www.nuget.org/packages/PublicApiGenerator/11.2.0
