### ISSUE TITLE
Replace CodeDom with Roslyn SyntaxFactory

### ISSUE THREAD

**Issue by danielmarbach** [PublicApiGenerator/PublicApiGenerator#86]
By taking a dependency to roslyn the whole code dom usage could be replaced with SyntaxFactory. For example

```
            var @namespace = SyntaxFactory.NamespaceDeclaration(SyntaxFactory.ParseName("SomePublicApi")).NormalizeWhitespace();

             // Add System using statement: (using System)
            //@namespace = @namespace.AddUsings(SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System")));

            //  Create a class: (class Order)
            var classDeclaration = SyntaxFactory.ClassDeclaration("Order");

            // Add the public modifier: (public class Order)
            classDeclaration = classDeclaration.AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword));

            // Inherit BaseEntity<T> and implement IHaveIdentity: (public class Order : BaseEntity<T>, IHaveIdentity)
            classDeclaration = classDeclaration.AddBaseListTypes(
                SyntaxFactory.SimpleBaseType(SyntaxFactory.ParseTypeName("BaseEntity<Order>")),
                SyntaxFactory.SimpleBaseType(SyntaxFactory.ParseTypeName("IHaveIdentity")));

            // Create a string variable: (bool canceled;)
            var variableDeclaration = SyntaxFactory.VariableDeclaration(SyntaxFactory.ParseTypeName("bool"))
                .AddVariables(SyntaxFactory.VariableDeclarator("canceled"));

            // Create a field declaration: (private bool canceled;)
            var fieldDeclaration = SyntaxFactory.FieldDeclaration(variableDeclaration)
                .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword));

            // Create a Property: (public int Quantity { get; set; })
            var propertyDeclaration = SyntaxFactory.PropertyDeclaration(SyntaxFactory.ParseTypeName("int"), "Quantity")
                .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
                .AddAccessorListAccessors(
                    SyntaxFactory.AccessorDeclaration(SyntaxKind.GetAccessorDeclaration).WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken)),
                    SyntaxFactory.AccessorDeclaration(SyntaxKind.SetAccessorDeclaration).WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken)));

            // Create a stament with the body of a method.
            var syntax = SyntaxFactory.ParseStatement("");

            // Create a method
            var methodDeclaration = SyntaxFactory.MethodDeclaration(SyntaxFactory.ParseTypeName("string"), "MarkAsCanceled")
                .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
                .WithBody(SyntaxFactory.Block(syntax));

            // Add the field, the property and method to the class.
            classDeclaration = classDeclaration.AddMembers(fieldDeclaration, propertyDeclaration, methodDeclaration);

            // Add the class to the namespace.
            @namespace = @namespace.AddMembers(classDeclaration);

            // Normalize and get code as string.
            var code = @namespace
                .NormalizeWhitespace()
                .ToFullString();
```

Generates an API to a string

Kudos to https://carlos.mendible.com/2017/03/02/create-a-class-with-net-core-and-roslyn/

**Comment by sungam3r** [comment]
I will be very happy with this change. The current way of generation through CodeCom is obscure.

**Comment by danielmarbach** [comment]
The SyntaxFactory is super hardcore to use. I spiked around a bit and it would take me too much time to iterate towards using the SyntaxFactory. I might explore the SyntaxGenerator a bit which seems to be less verbose

https://gist.github.com/jagt/1b77a3c6e2c0ba2aea1ca437997289f2

**Comment by sungam3r** [comment]
But isn’t it easier to write your own renderer? Because the bodies of the methods are not needed, only the signatures.

**Comment by sungam3r** [comment]
I think that standard System.Reflection is enough to solve the problem.

**Comment by danielmarbach** [comment]
Sorry I don't understand your input about reflection.

Well define easier ;)

Probably the easiest way, for now, would be string templating. This issue is more a way of publicly capturing my current thought process. Not sure I have the capacity to execute on it

**Comment by sungam3r** [comment]
> Sorry I don't understand your input about reflection.

Use standard System.Reflection API instead Mono, Roslyn to read assembly information and build public api as text manually. This should not require writing more code than there is now.

**Comment by danielmarbach** [comment]
Reflection brings a host of other problems like assembly loading into app domain. With mono.cecil that problem doesn't exist. So I'm not sure I'd see that value in that. Plus some information that is currently available with Mono.Cecil would be hard or even impossible to retrieve with reflection. The new reflection api might work but it is obscure and not well documented yet

**Comment by sungam3r** [comment]
Ok.

> Plus some information that is currently available with Mono.Cecil would be hard or even impossible to retrieve with reflection.

For example, what?

**Comment by danielmarbach** [comment]
Looked a bit more into using the SyntaxGenerator. The basic bits where easy to get started but now I'm a bit stuck to get the return type expressions done properly

https://github.com/JakeGinnivan/ApiApprover/tree/roslyn-spike

**Comment by danielmarbach** [comment]
I confess I'm not really keen to bring this forward. I did another attempt last night and rebuilding everything with SyntaxFactory is painstakingly tiresome especially because I would need to make sure everything is still compatible. 

Every time I give it another attempt I spend hours of diving through poorly documented roslyn APIs, using [Oren's Roslyin Quoter](https://roslynquoter.azurewebsites.net/) to get a tiny sense of what is going on until my head explodes and I ask myself why I'm going through all this pain.

I tried different psychological tricks like convincing myself that this is a really rewarding learning experience but that didn't help

**Comment by sungam3r** [comment]
Perhaps later api will be simplified.

**Comment by jnm2** [comment]
I had a lot of fun rendering to a StringBuilder directly. A bit messy to put it all in one file, but I found it very easy to tweak.

https://github.com/jnm2/ApiContractGenerator/blob/46a90b471b1d724e2fb8109ae86f5f195e5edc65/src/ApiContractGenerator/CSharpTextFormatter.cs

**Comment by danielmarbach** [comment]
Found this https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.GenAPI

**Comment by danielmarbach** [comment]
I'm not going to put any more efforts into rewriting the core of this library given that Microsoft is pushing the GenAPI forward and I've already seen some projects adopting it. Closing this issue
